name: Build
on:
  pull_request:
    types: [ opened, ready_for_review, reopened, synchronize ]
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v3

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Copy Secrets
        run: cp secrets.default.properties secrets.properties

      - uses: ./.github/actions/setup-java

      - uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
        with:
          path: ~/.gradle/wrapper
          key: gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      - uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
        with:
          path: |
            ~/.gradle/caches/build-cache-*
            ~/.gradle/caches/[0-9]*.*
            .gradle
          key: ${{ runner.os }}-gradle-build-${{ github.workflow }}-${{ github.sha }}
          restore-keys: ${{ runner.os }}-gradle-build-${{ github.workflow }}-

      - name: Setup Gradle
        uses: gradle/gradle-build-action@ac2d340dc04d9e1113182899e983b5400c17cda1 # v3.5.0

      - name: Build all build type and flavor permutations
        run: ./gradlew assemble --stacktrace

#      - name: Upload build outputs (APKs)
#        uses: actions/upload-artifact@v4
#        with:
#          name: build-outputs
#          path: app/build/outputs

#      - name: Slack Notification Success
#        uses: rtCamp/action-slack-notify@v2
#        env:
#          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
#          SLACK_TITLE: 'Message'
#          SLACK_MESSAGE: 'Android Build Success :rocket: ${{ github.repository }}'
#          SLACK_COLOR: ${{ job.status }}
#
#      - name: Slack Notification Failure
#        if: failure()
#        uses: rtCamp/action-slack-notify@v2
#        env:
#          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
#          SLACK_TITLE: 'Message'
#          SLACK_MESSAGE: 'Android Build Failure :mask: ${{ github.repository }}'
#          SLACK_COLOR: ${{ job.status }}
