name: Check
on:
  pull_request:
    types: [ opened, ready_for_review, reopened, synchronize ]
  push:
    branches:
      - main

jobs:
  lint-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: ktlint
        uses: ScaCap/action-ktlint@26c5e9b625966139d9956cbbb6217375480d4e14 # v1.9.0
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          fail_on_error: true
      
      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Copy Secrets
        run: cp secrets.default.properties secrets.properties

      - name: lint
        run: ./gradlew lint
