name: Check
on:
  pull_request:

jobs:
  ktlint:
    name: Ktlint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: ktlint
        uses: ScaCap/action-ktlint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          fail_on_error: true
