name: Check
on:
  pull_request:
    types: [ opened, ready_for_review, reopened, synchronize ]

jobs:
  ktlint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: ktlint
        uses: ScaCap/action-ktlint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          fail_on_error: true
