name: unit-test

on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, ready_for_review, reopened, synchronize ]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    permissions:
      contents: read # for clone
      actions: write # for upload-artifact

    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Copy Secrets
        run: cp secrets.default.properties secrets.properties

      - uses: ./.github/actions/setup-java

      - name: Upload an event payload for EnricoMi/publish-unit-test-result-action
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: event-payload
          path: ${{ github.event_path }}

      - run: ./gradlew testDebugUnitTest --stacktrace

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        if: always()
        with:
          name: test-reports
          path: |
            **/reports
